### ISSUE TITLE
TypeError while doing Subdomain enumeration

### ISSUE THREAD

**Issue by BahatiPhill** [GitHackTools/BillCipher#1]
` File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 566, in enumerate
    if 'Next page' not in resp:
TypeError: argument of type 'int' is not iterable
`

**Comment by gitkern3l** [comment]
Sorry for late response!
Did you run BillCipher in Python 3 or 2?
